
server:
  port: 1005

spring:
  application:
    name: STUDENT-SERVER

  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=Asia/Seoul
    name: LMS-SERVER

  datasource:
    url: jdbc:mysql://localhost:3306/lms?serverTimezone=Asia/Seoul

    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}